create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text,
  items jsonb not null,
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer not null default 0 check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'delivering', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

grant usage, select on sequence public.orders_id_seq to anon, authenticated;
grant insert, select on public.orders to anon, authenticated;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'orders'
  loop
    execute format('drop policy if exists %I on public.orders', policy_record.policyname);
  end loop;
end
$$;

create policy "Anyone can create an order"
on public.orders for insert
to public
with check (true);

create policy "Anyone can read an order id after creating it"
on public.orders for select
to public
using (true);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
